---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart elasticsearch through systemd
  become: yes
  service:
    name: elasticsearch
    state: restarted
  listen: "restart elasticsearch"
  when:
    - not elasticsearch_disable_install or elasticsearch_instaled
    - not ansible_check_mode

- name: custom | restart elasticsearch service through systemd
  service:
    name: "{{ custom_elasticsearch_service_name }}"
    state: restarted
  listen: "restart custom_elasticsearch"
  when:
    - not elasticsearch_disable_install or elasticsearch_instaled
    - not ansible_check_mode
